VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsContexts"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'Option Explicit
'
'Public Count As Long
'Private moContexts() As clsContext
'
'Public Function AddContext(oMember As clsContext)
'    ReDim Preserve moContexts(Count)
'    Set moContexts(Count) = oMember
'    Count = Count + 1
'End Function
'
'Public Property Get Contexts(ByVal lIndex As Long) As clsContext
'    Set Contexts = moContexts(lIndex)
'End Property
'
'Public Property Set Contexts(ByVal lIndex As Long, oMember As clsContext)
'    Set moContexts(lIndex) = oMember
'End Property
'
'
'
